# ===================================
#  Form Behavior Config
# ===================================

name: Blog post
form: $/rainlab/blog/models/post/fields.yaml
modelClass: RainLab\Blog\Models\Post
defaultRedirect: rainlab/blog/posts

create:
    redirect: rainlab/blog/posts/update/:id
    redirectClose: rainlab/blog/posts
    design:
        displayMode: document

update:
    redirect: rainlab/blog/posts
    redirectClose: rainlab/blog/posts
    design:
        displayMode: document
